name: pumped_end_device
description:  >-
  Pumped Fuel is a combination of 3 core projects to connect
  vehicle drivers with retail merchants, initially starting
  with fuel stations. Our objective is to offer the best fuel
  prices, closest stations, friendliest service, cleanest restrooms,
  tastiest coffee and so much more, direct to vehicle drivers.
  Pumped End Device (ped) is the IVI presentation layer
homepage: https://www.pumpedfuel.com/
repository: https://github.com/bernardpumped/ped/tree/agl
issue_tracker: https://github.com/bernardpumped/ped/issues
documentation: https://github.com/bernardpumped/ped/tree/agl#readme
version: 1.0.0+45

# IVI branch's are landscape and specific to web, linux and custom Yocto/AGL
platforms:
  linux:
    web:

environment:
  flutter: '>=3.13.8'
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  async: ^2.10.0
  basic_utils: ^5.7.0
#  fl_chart: ^0.64.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
#  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.1
  geolocator: ^10.1.0                                                          # <-- linux not supported todo add geoclue
  get_it: ^7.2.0
  http: ^1.1.0
  intl: ^0.18.1
  localstore: ^1.3.5
  provider: ^6.0.5
#  rate_my_app: ^2.0.0
  sprintf: ^7.0.0
  url_launcher: ^6.1.10
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^1.0.0
  dependency_validator: ^3.2.3
  flutter_driver:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/ic_splash.png
    - assets/images/1.0x/ic_splash.png
    - assets/images/2.0x/ic_splash.png
    - assets/images/3.0x/ic_splash.png
    - assets/images/ic_car_service.svg
    - assets/images/1.0x/ic_car_service.svg
    - assets/images/2.0x/ic_car_service.svg
    - assets/images/3.0x/ic_car_service.svg
    - assets/images/ic_pumped_black_text.png
    - assets/images/1.0x/ic_pumped_black_text.png
    - assets/images/2.0x/ic_pumped_black_text.png
    - assets/images/3.0x/ic_pumped_black_text.png
    - assets/images/ic_user.png
    - assets/images/Wave-2-landscape.png #https://bgjar.com/wave
    - assets/images/1.0x/ic_user.png
    - assets/images/2.0x/ic_user.png
    - assets/images/3.0x/ic_user.png

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages