name: pumped_end_device
description: Pumped End Device

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# packages
  basic_utils: ^4.2.2
  floating_action_bubble: ^1.1.4
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_svg: ^1.0.3
  fl_chart: ^0.55.0
  get_it: ^7.2.0
  http: ^0.13.3
  implicitly_animated_reorderable_list: ^0.4.1
  intl: ^0.17.0
  localstore: ^1.2.0
  sprintf: ^6.0.0
  uuid: ^3.0.4

# plugins general
  device_info_plus: ^4.0.0
  fluttertoast: ^8.0.9
  geocoding: ^2.0.4
  geolocator: ^9.0.0
  geolocator_linux: ^0.1.0
  path: ^1.8.0 # Supported on Linux
  url_launcher: ^6.0.11 # Supported on Linux. However, for certain functions invoked using this library do not work on Linux, like google maps, phone calling etc.
  webview_flutter: ^3.0.4 # NOT supported on linux.

dev_dependencies:
  build_runner: ^2.1.5
  change_app_package_name: ^1.0.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  pedantic: ^1.11.1
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/ic_splash.png
    - assets/images/1.0x/ic_splash.png
    - assets/images/2.0x/ic_splash.png
    - assets/images/3.0x/ic_splash.png
    - assets/images/ic_car_service.svg
    - assets/images/1.0x/ic_car_service.svg
    - assets/images/2.0x/ic_car_service.svg
    - assets/images/3.0x/ic_car_service.svg
    - assets/images/ic_pumped_black_text.png
    - assets/images/1.0x/ic_pumped_black_text.png
    - assets/images/2.0x/ic_pumped_black_text.png
    - assets/images/3.0x/ic_pumped_black_text.png
    - assets/images/ic_user.png
    - assets/images/Wave-2-landscape.png #https://bgjar.com/wave
    - assets/images/1.0x/ic_user.png
    - assets/images/2.0x/ic_user.png
    - assets/images/3.0x/ic_user.png

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
