/*
 *     Copyright (c) 2022.
 *     This file is part of Pumped End Device.
 *
 *     Pumped End Device is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     Pumped End Device is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with Pumped End Device.  If not, see <https://www.gnu.org/licenses/>.
 */

// Mocks generated by Mockito 5.0.16 from annotations
// in pumped_end_device/test/data/local/location/location_data_source_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as i1;
import 'package:pumped_end_device/data/local/location/geo_location_wrapper.dart' as i3;
import 'package:pumped_end_device/util/platform_wrapper.dart' as i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PlatformWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformWrapper extends i1.Mock implements i2.PlatformWrapper {
  MockPlatformWrapper() {
    i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GeoLocationWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeoLocationWrapper extends i1.Mock implements i3.GeoLocationWrapper {
  MockGeoLocationWrapper() {
    i1.throwOnMissingStub(this);
  }
}
